# Default logger configuration for EEG experiments

defaults:
  - csv
  # - wandb
  - _self_

csv:
  _target_: pytorch_lightning.loggers.csv_logs.CSVLogger
  save_dir: "${paths.output_dir}"
  name: "csv/"
  prefix: ""

# wandb:
#   _target_: pytorch_lightning.loggers.wandb.WandbLogger
#   name: "${name}"
#   save_dir: "${paths.output_dir}"
#   offline: false
#   id: null
#   project: "eeg-classification"
#   log_model: false
#   prefix: ""
#   group: ""
#   tags: ${tags}
#   job_type: ""

