# Default loader configuration for EEG experiments

train:
  batch_size: 128
  shuffle: true
  num_workers: 0
  drop_last: true
  pin_memory: false
  persistent_workers: false

valid:
  batch_size: 128
  shuffle: false
  num_workers: 0
  drop_last: false
  pin_memory: false
  persistent_workers: false

test:
  batch_size: 128
  shuffle: false
  num_workers: 0
  drop_last: false
  pin_memory: false
  persistent_workers: false

predict:
  batch_size: 128
  shuffle: false
  num_workers: 0
  drop_last: false
  pin_memory: false
  persistent_workers: false

