_target_: src.datamodules.datamodules.SingleDataModule

defaults:
  - _self_
  - loaders: eeg_loaders.yaml
  - transforms: eeg_transforms.yaml

# EEG datasets configuration
# data_path should be specified per experiment
datasets:
  train:
    _target_: src.datamodules.datasets.ClassificationDataset
    path_column: crop_path
    target_column: target
    read_mode: npy
    include_names: false
    label_type: "torch.LongTensor"

  valid:
    _target_: src.datamodules.datasets.ClassificationDataset
    path_column: crop_path
    target_column: target
    read_mode: npy
    include_names: false
    label_type: "torch.LongTensor"

  test:
    _target_: src.datamodules.datasets.ClassificationDataset
    path_column: crop_path
    target_column: target
    read_mode: npy
    include_names: false
    label_type: "torch.LongTensor"
